---
- name: Auto Remediate High CPU
  hosts: windows
  gather_facts: yes
  vars:
    cpu_threshold: 30

  tasks:
    - include_tasks: diagnose.yml

    - include_tasks: remediate.yml

    - include_tasks: validate.yml
