---
- name: Auto Remediate High CPU
  hosts: windows
  gather_facts: yes

  vars:

    cpu_threshold: 30
    max_remediation_attempts: 5

    protected_processes:
      - System
      - Idle
      - svchost
      - lsass
      - csrss
      - services
      - wininit
      - winlogon
      - MsMpEng
      - sqlservr
      - explorer

  tasks:

    - include_tasks: diagnose.yml

    - include_tasks: remediate.yml

    - include_tasks: validate.yml
