---
- name: Initialize variables
  set_fact:
    current_cpu: "{{ cpu_before.stdout | float }}"
    remediation_attempt: 0

- name: Remediation Loop
  include_tasks: remediation_attempt.yml
  loop: "{{ range(1, max_remediation_attempts + 1) | list }}"
  loop_control:
    loop_var: attempt
  when: current_cpu | float > cpu_threshold
