---
- name: Get Highest CPU Process
  ansible.windows.win_shell: |
    $proc = Get-Process |
      Sort-Object CPU -Descending |
      Select-Object -First 1

    $proc.Name
  register: top_process

- name: Display Process
  debug:
    msg: "Top CPU Process: {{ top_process.stdout }}"

- name: Check If Process Is Protected
  set_fact:
    protected_process: "{{ top_process.stdout | trim in protected_processes }}"

- name: Display Protection Status
  debug:
    msg: >
      Process {{ top_process.stdout }}
      Protected = {{ protected_process }}

- name: Stop Non-Protected Process
  ansible.windows.win_shell: |
    $proc = Get-Process |
      Sort-Object CPU -Descending |
      Select-Object -First 1

    Stop-Process -Id $proc.Id -Force

    Write-Output $proc.Name
  register: remediation_result
  when: not protected_process

- name: Display Remediation Result
  debug:
    msg: "Stopped Process: {{ remediation_result.stdout }}"
  when: not protected_process

- name: Skip Protected Process
  debug:
    msg: >
      Process {{ top_process.stdout }}
      is protected. Automated remediation skipped.
  when: protected_process
